// Copyright 2026 Google LLC
// SPDX-License-Identifier: Apache-2.0

namespace JulesSdk.Models;

/// <summary>
/// A file generated by a session, with full content extracted from the diff.
/// </summary>
public record GeneratedFile(
    string Path,
    ChangeType ChangeType,
    string Content,
    int Additions,
    int Deletions
);

/// <summary>
/// A collection of generated files with helper methods for ergonomic access.
/// </summary>
public class GeneratedFiles
{
    private readonly IReadOnlyList<GeneratedFile> _files;
    
    public GeneratedFiles(IReadOnlyList<GeneratedFile> files)
    {
        _files = files;
    }
    
    /// <summary>
    /// Returns all generated files.
    /// </summary>
    public IReadOnlyList<GeneratedFile> All() => _files;
    
    /// <summary>
    /// Find a file by its path.
    /// </summary>
    public GeneratedFile? Get(string path) => _files.FirstOrDefault(f => f.Path == path);
    
    /// <summary>
    /// Filter files by change type.
    /// </summary>
    public IReadOnlyList<GeneratedFile> Filter(ChangeType changeType) => 
        _files.Where(f => f.ChangeType == changeType).ToList();
}
