// Copyright 2026 Google LLC
// SPDX-License-Identifier: Apache-2.0

using JulesSdk.Utilities;

namespace JulesSdk.Models;

/// <summary>
/// The final outcome of a completed session or run.
/// </summary>
public class Outcome
{
    /// <summary>
    /// The session ID.
    /// </summary>
    public string? SessionId { get; init; }
    
    /// <summary>
    /// The title of the session.
    /// </summary>
    public string? Title { get; init; }
    
    /// <summary>
    /// The final state ("completed" or "failed").
    /// </summary>
    public SessionState State { get; init; }
    
    /// <summary>
    /// The primary Pull Request created by the session, if applicable.
    /// </summary>
    public PullRequest? PullRequest { get; init; }
    
    /// <summary>
    /// All outputs generated by the session.
    /// </summary>
    public IReadOnlyList<SessionOutput>? Outputs { get; init; }
    
    /// <summary>
    /// Activities containing artifacts (changesets, media, etc). 
    /// Populated when streaming activities or fetching session history.
    /// </summary>
    public IReadOnlyList<Activity>? Activities { get; init; }
    
    /// <summary>
    /// Returns all files generated by this session with their full content.
    /// Requires Activities to be populated (via StreamAsync or HistoryAsync).
    /// </summary>
    public GeneratedFiles GeneratedFiles()
    {
        var files = new List<GeneratedFile>();
        
        if (Activities != null)
        {
            foreach (var activity in Activities)
            {
                if (activity.Artifacts == null) continue;
                
                foreach (var artifact in activity.Artifacts)
                {
                    // Check for changeset in the union field
                    if (artifact.ChangeSet?.GitPatch?.UnidiffPatch != null)
                    {
                        var parsed = UnidiffParser.ParseWithContent(artifact.ChangeSet.GitPatch.UnidiffPatch);
                        files.AddRange(parsed);
                    }
                }
            }
        }
        
        return new GeneratedFiles(files);
    }
}

