// Copyright 2026 Google LLC
// SPDX-License-Identifier: Apache-2.0

using JulesSdk.Utilities;

namespace JulesSdk.Models;

/// <summary>
/// The final outcome of a completed session or run.
/// </summary>
public class Outcome
{
    /// <summary>
    /// The session ID.
    /// </summary>
    public required string SessionId { get; init; }
    
    /// <summary>
    /// The title of the session.
    /// </summary>
    public required string Title { get; init; }
    
    /// <summary>
    /// The final state ("completed" or "failed").
    /// </summary>
    public required SessionState State { get; init; }
    
    /// <summary>
    /// The primary Pull Request created by the session, if applicable.
    /// </summary>
    public PullRequest? PullRequest { get; init; }
    
    /// <summary>
    /// All outputs generated by the session.
    /// </summary>
    public required IReadOnlyList<SessionOutput> Outputs { get; init; }
    
    /// <summary>
    /// Returns all files generated by this session with their full content.
    /// </summary>
    public GeneratedFiles GeneratedFiles()
    {
        var files = new List<GeneratedFile>();
        
        foreach (var output in Outputs)
        {
            if (output.Type == "changeSet" && output.ChangeSet?.GitPatch != null)
            {
                var parsed = UnidiffParser.ParseWithContent(output.ChangeSet.GitPatch.UnidiffPatch);
                files.AddRange(parsed);
            }
        }
        
        return new GeneratedFiles(files);
    }
}
