// Copyright 2026 Google LLC
// SPDX-License-Identifier: Apache-2.0

using JulesSdk.Utilities;

namespace JulesSdk.Models;

/// <summary>
/// The final outcome of a completed session or run.
/// </summary>
public class SessionOutcome
{
    /// <summary>
    /// The session ID.
    /// </summary>
    public string? SessionId { get; init; }
    
    /// <summary>
    /// The title of the session.
    /// </summary>
    public string? Title { get; init; }
    
    /// <summary>
    /// The final state ("completed" or "failed").
    /// </summary>
    public SessionState State { get; init; }
    
    /// <summary>
    /// The primary Pull Request created by the session, if applicable.
    /// </summary>
    public PullRequest? PullRequest { get; init; }
    
    /// <summary>
    /// All outputs generated by the session.
    /// </summary>
    public IReadOnlyList<SessionOutput>? Outputs { get; init; }
    
    /// <summary>
    /// Activities containing artifacts (changesets, media, etc). 
    /// Populated when streaming activities or fetching session history.
    /// </summary>
    public IReadOnlyList<Activity>? Activities { get; init; }
    
    /// <summary>
    /// Returns all files generated by this session with their full content.
    /// Requires Activities to be populated (via StreamAsync or HistoryAsync).
    /// </summary>
    public GeneratedFiles GeneratedFiles()
    {
        var files = new List<GeneratedFile>();
        
        if (Activities != null)
        {
            foreach (var activity in Activities)
            {
                if (activity.Artifacts == null) continue;
                
                foreach (var artifact in activity.Artifacts)
                {
                    // Check for changeset in the union field
                    if (artifact.ChangeSet?.GitPatch?.UnidiffPatch != null)
                    {
                        var parsed = UnidiffParser.ParseWithContent(artifact.ChangeSet.GitPatch.UnidiffPatch);
                        files.AddRange(parsed);
                    }
                }
            }
        }
        
        return new GeneratedFiles(files);
    }
    
    /// <summary>
    /// Returns the first changeset artifact if one exists, providing access to 
    /// the unified diff and parsed file changes.
    /// </summary>
    /// <example>
    /// <code>
    /// var result = await session.ResultAsync();
    /// var changeSet = result.ChangeSet();
    /// if (changeSet != null)
    /// {
    ///     var parsed = changeSet.Parse();
    ///     Console.WriteLine($"{parsed.Summary.TotalFiles} files changed");
    /// }
    /// </code>
    /// </example>
    /// <returns>The first ChangeSetData from activities, or null if none exists.</returns>
    public ChangeSetData? ChangeSet()
    {
        if (Activities == null) return null;
        
        foreach (var activity in Activities)
        {
            if (activity.Artifacts == null) continue;
            
            foreach (var artifact in activity.Artifacts)
            {
                if (artifact.ChangeSet != null)
                    return artifact.ChangeSet;
            }
        }
        
        return null;
    }
}

/// <summary>
/// Type alias for backward compatibility.
/// </summary>
[Obsolete("Use SessionOutcome instead.")]
public class Outcome : SessionOutcome { }
